version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Check prettier
          command: yarn run check-format
      - run:
          name: Check eslint
          command: yarn run check-lint
      - run:
          name: Run tests
          command: yarn run test

workflows:
  commit:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: prod
