import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MainLayout from "src/components/hoc/MainLayout";

const ProjectDetail: NextPage = () => {
  return (
    <MainLayout>
      <div className="tw-w-full wt-h-full">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        detail
      </div>
    </MainLayout>
  );
};

export default ProjectDetail;
