#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
yarn run check-format ||
(
    echo 'Prettier Check Failed. Run yarn run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
